### ISSUE TITLE
Action buttons style missing on the documentation

### ISSUE THREAD

**Issue by fabiomolinar** [Collaborne/paper-fab-speed-dial#6]
The documentation is not clear on how to set up the styles of the inner paper-fab buttons which belongs to the paper-fab-speed-dial-action elements. 

I would add to the documentation that to style the inner buttons one have to use the following variables:
```
--paper-fab-speed-dial-action-background;
--paper-fab-speed-dial-action-keyboard-focus-background
```

**Comment by ankon** [comment]
There is documentation regarding these styles on these action elements: http://collaborne.github.io/paper-fab-speed-dial/components/paper-fab-speed-dial/#paper-fab-speed-dial-action. 

Could you maybe suggest a better wording, or where else this should be referenced?

**Comment by fabiomolinar** [comment]
Maybe it is just a matter of making it clear that the styles for the `paper-fab-speed-dial` are not inherited by the `paper-fab-speed-dial-action`. At first I thought that changing the styles for `paper-fab-speed-dial` would be enough to also style the `action` elements. But they are separated and the latter don't inherit from the former.

**Comment by ronnyroeller** [comment]
> But they are separated and the latter don't inherit from the former.

That looks to me pretty much in line as Polymer elements are supposed to work (isolate styling)... or are I'm missing something?

**Comment by fabiomolinar** [comment]
Yes, keeping scopes isolated is how Polymer is supposed to work. But I don't believe it means that elements that are contained inside others can't have their **defaults** styles inherited from parent elements. After all, isn't inheritance one of the advantages of CSS/HTML styling?

**Comment by ronnyroeller** [comment]
> But I don't believe it means that elements that are contained inside others can't have their defaults styles inherited from parent elements. 

Not sure about this. Could you please point me to the relevant documentation on polymer-project.org ?

**Comment by fabiomolinar** [comment]
I'm also not sure. I'm not a Polymer expert. Just got to learn it a few weeks ago. Not sure if it would work, but would something like the following do the trick?

**paper-fab-speed-dial-action.html**
```
.fab {
   --paper-fab-background: var(--paper-fab-speed-dial-action-background, --paper-fab-speed-dial-background);
   --paper-fab-keyboard-focus-background: var(--paper-fab-speed-dial-action-keyboard-focus-background);
}
```

**Comment by ronnyroeller** [comment]
I think the most comparable thing in from Polymer Elements are `<paper-tabs>` for which the mixin are also on the tab level (not parent level). See https://www.webcomponents.org/element/PolymerElements/paper-tabs/paper-tab

So, I'd say it's best to keep the current behavior a this seems to be in line with Polymer best practices.
