### ISSUE TITLE
Remove gray screen background when dial is opened

### ISSUE THREAD

**Issue by TakhirMamirov** [Collaborne/paper-fab-speed-dial#7]
Is there any way to remove the gray full screen overlay when the speed dial is opened? I need it mostly as Google does: https://inbox.google.com.

**Comment by ronnyroeller** [comment]
Not right now.
Feel free to provide a PR to expose the `with-backdrop` property of the overlay:
https://github.com/Collaborne/paper-fab-speed-dial/blob/master/paper-fab-speed-dial.html#L59
