### ISSUE TITLE
Backdrop in front of fab-speed-dial-actions

### ISSUE THREAD

**Issue by visconde** [Collaborne/paper-fab-speed-dial#8]
I was trying to use this element

however, same code from the demo, when i click on the main FAB button, the backdrop gets on top of the speed-dial-actions

<img width="365" alt="screen shot 2017-05-28 at 13 38 22" src="https://cloud.githubusercontent.com/assets/2545916/26528835/a04b3750-43ab-11e7-8262-7a6cf0cff437.png">

any guess why ?

as a hack im disabling the back-drop , but would prefer not to do it :)

**Comment by ronnyroeller** [comment]
It's caused by Polymer's overlay stack context. See e.g.: https://github.com/PolymerElements/iron-overlay-behavior/issues/208#issuecomment-234024428

The easiest solution is to attach the FAB to the document body (or another point high in the DOM tree of your application):
```
ready: function() {
  // Attach dialog to the body to ensure it's on top of all existing overlays
  Polymer.dom(document.body).appendChild(this.$.fab);
},
```

**Comment by heymitul** [comment]
@ronnyroeller it worked fine for me !! 
Thank you very much
